//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Of_Sale
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.EpmloyeeSalaries = new HashSet<EpmloyeeSalary>();
        }
    
        public int ID { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        [Display(Name = "Name")]
        public string EmployeeName { get; set; }

        [Required]
        [StringLength(14, MinimumLength = 11)]
        [DataType(DataType.PhoneNumber)]
        [Display(Name = "Contact")]
        public string EmployeeContact { get; set; }

        [Required]
        [StringLength(50, MinimumLength = 2)]
        [Display(Name = "Email")]
        [DataType(DataType.EmailAddress)]
        public string EmployeeEmail { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string EmployeePassword { get; set; }

        [Required]
        [Display(Name = "Gender")]
        public bool EmployeeGender { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "Join Date")]
        public System.DateTime EmployeeJoinDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "DOB")]
        public System.DateTime EmployeeDateOfBirth { get; set; }

        [Required]
        [StringLength(500, MinimumLength = 2)]
        [Display(Name = "Address")]
        [DataType(DataType.MultilineText)]
        public string EmployeeAddress { get; set; }

        [Required]
        [Display(Name = "Select City")]
        public int EmployeeCityID { get; set; }

        [Required]
        [Display(Name = "Image")]
        [DataType(DataType.ImageUrl)]
        public string EmployeePicture { get; set; }
    
        public virtual City City { get; set; }
        public virtual EmployeeAdmin EmployeeAdmin { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EpmloyeeSalary> EpmloyeeSalaries { get; set; }
    }
}
