//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Point_Of_Sale
{
    using System;
    using System.Collections.Generic;
    
    public partial class EpmloyeeSalary
    {
        public int ID { get; set; }
        public int EmployeeID { get; set; }
        public double EmployeeSalary { get; set; }
        public System.DateTime SalaryMonth { get; set; }
        public System.DateTime SalaryReciveDate { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
